/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aufgabe4.view;

import aufgabe4.model.AdressverwaltungModel;

/**
 *
 * @author jnas1
 */
public class Window extends javax.swing.JFrame
{

    /**
     * @return the jMenuEditUndo
     */
    public javax.swing.JMenuItem getjMenuEditUndo()
    {
        return jMenuEditUndo;
    }

    /**
     * @return the jBtnUndo
     */
    public javax.swing.JButton getjBtnUndo()
    {
        return jBtnUndo;
    }

    /**
     * @return the jMenuUndo
     */
    public javax.swing.JMenuItem getjMenuUndo()
    {
        return getjMenuEditUndo();
    }

    /**
     * @return the jPopupUndo
     */
    public javax.swing.JMenuItem getjPopupUndo()
    {
        return jPopupUndo;
    }

    /**
     * @return the jMenuEditRemove
     */
    public javax.swing.JMenuItem getjMenuEditRemove()
    {
        return jMenuEditRemove;
    }

    /**
     * @return the jBtnRemove
     */
    public javax.swing.JButton getjBtnRemove()
    {
        return jBtnRemove;
    }

    /**
     * @return the jPopupRemove
     */
    public javax.swing.JMenuItem getjPopupRemove()
    {
        return jPopupRemove;
    }

    /**
     * @return the jBtnAdd
     */
    public javax.swing.JButton getjBtnAdd()
    {
        return jBtnAdd;
    }

    /**
     * @return the jMenuEdidAdd
     */
    public javax.swing.JMenuItem getjMenuEditAdd()
    {
        return jMenuEditAdd;
    }

    /**
     * @return the jPopupAdd
     */
    public javax.swing.JMenuItem getjPopupAdd()
    {
        return jPopupAdd;
    }

    /**
     * @return the jTable
     */
    public javax.swing.JTable getjTable()
    {
        return jTable;
    }

    /**
     * @return the jMenuPopupOpen
     */
    public javax.swing.JMenuItem getjMenuPopupOpen()
    {
        return jPopupOnFileOpen;
    }

    /**
     * @return the jBtnOpen
     */
    public javax.swing.JButton getjBtnOpen()
    {
        return jBtnOpen;
    }

    /**
     * @return the jBtnSave
     */
    public javax.swing.JButton getjBtnSave()
    {
        return jBtnSave;
    }

    /**
     * @return the jLblFile
     */
    public javax.swing.JLabel getjLblFile()
    {
        return jLblFile;
    }

    /**
     * @return the jMenuFileOpen
     */
    public javax.swing.JMenuItem getjMenuFileOpen()
    {
        return jMenuFileOpen;
    }

    /**
     * @return the jMenuFileSave
     */
    public javax.swing.JMenuItem getjMenuFileSave()
    {
        return jMenuFileSave;
    }

    /**
     * @return the jPopupOpen
     */
    public javax.swing.JMenuItem getjPopupOpen()
    {
        return jPopupOpen;
    }

    /**
     * @return the jPopupSave
     */
    public javax.swing.JMenuItem getjPopupSave()
    {
        return jPopupSave;
    }

    /**
     * Creates new form Window
     */
    public Window()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenuAddressbook = new javax.swing.JPopupMenu();
        jPopupOpen = new javax.swing.JMenuItem();
        jPopupSave = new javax.swing.JMenuItem();
        jPopupAdd = new javax.swing.JMenuItem();
        jPopupRemove = new javax.swing.JMenuItem();
        jPopupUndo = new javax.swing.JMenuItem();
        jFileChooser = new javax.swing.JFileChooser();
        jPopupMenuOpen = new javax.swing.JPopupMenu();
        jPopupOnFileOpen = new javax.swing.JMenuItem();
        jToolBar = new javax.swing.JToolBar();
        jPanel = new javax.swing.JPanel();
        jBtnOpen = new javax.swing.JButton();
        jBtnSave = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtnRemove = new javax.swing.JButton();
        jBtnUndo = new javax.swing.JButton();
        jLblFile = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuFileOpen = new javax.swing.JMenuItem();
        jMenuFileSave = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuEditAdd = new javax.swing.JMenuItem();
        jMenuEditRemove = new javax.swing.JMenuItem();
        jMenuEditUndo = new javax.swing.JMenuItem();

        jPopupOpen.setText("Open");
        jPopupMenuAddressbook.add(jPopupOpen);

        jPopupSave.setText("Save");
        jPopupMenuAddressbook.add(jPopupSave);

        jPopupAdd.setText("Add");
        jPopupMenuAddressbook.add(jPopupAdd);

        jPopupRemove.setText("Remove");
        jPopupMenuAddressbook.add(jPopupRemove);

        jPopupUndo.setText("Undo");
        jPopupMenuAddressbook.add(jPopupUndo);

        jPopupOnFileOpen.setText("Open");
        jPopupMenuOpen.add(jPopupOnFileOpen);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar.setRollover(true);

        jPanel.setLayout(new javax.swing.BoxLayout(jPanel, javax.swing.BoxLayout.LINE_AXIS));

        jBtnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Open24.gif"))); // NOI18N
        jBtnOpen.setToolTipText("Open");
        jBtnOpen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnOpenActionPerformed(evt);
            }
        });
        jPanel.add(jBtnOpen);

        jBtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Save24.gif"))); // NOI18N
        jBtnSave.setToolTipText("Save");
        jBtnSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnSaveActionPerformed(evt);
            }
        });
        jPanel.add(jBtnSave);

        jBtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Add24.gif"))); // NOI18N
        jBtnAdd.setToolTipText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAddActionPerformed(evt);
            }
        });
        jPanel.add(jBtnAdd);

        jBtnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Delete24.gif"))); // NOI18N
        jBtnRemove.setToolTipText("Delete");
        jPanel.add(jBtnRemove);

        jBtnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Undo24.gif"))); // NOI18N
        jBtnUndo.setToolTipText("Undo");
        jBtnUndo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnUndoActionPerformed(evt);
            }
        });
        jPanel.add(jBtnUndo);

        jToolBar.add(jPanel);

        getContentPane().add(jToolBar, java.awt.BorderLayout.PAGE_START);

        jLblFile.setComponentPopupMenu(jPopupMenuOpen);
        getContentPane().add(jLblFile, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setComponentPopupMenu(jPopupMenuAddressbook);
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenuFile.setMnemonic('F');
        jMenuFile.setText("File");

        jMenuFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuFileOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Open16.gif"))); // NOI18N
        jMenuFileOpen.setText("Open");
        jMenuFile.add(jMenuFileOpen);

        jMenuFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuFileSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Save16.gif"))); // NOI18N
        jMenuFileSave.setText("Save");
        jMenuFile.add(jMenuFileSave);

        jMenuBar.add(jMenuFile);

        jMenuEdit.setMnemonic('E');
        jMenuEdit.setText("Edit");

        jMenuEditAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Add16.gif"))); // NOI18N
        jMenuEditAdd.setText("Add");
        jMenuEdit.add(jMenuEditAdd);

        jMenuEditRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Delete16.gif"))); // NOI18N
        jMenuEditRemove.setText("Remove");
        jMenuEdit.add(jMenuEditRemove);

        jMenuEditUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuEditUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe4/view/icons/Undo16.gif"))); // NOI18N
        jMenuEditUndo.setText("Undo");
        jMenuEdit.add(jMenuEditUndo);

        jMenuBar.add(jMenuEdit);

        setJMenuBar(jMenuBar);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnOpenActionPerformed
    {//GEN-HEADEREND:event_jBtnOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnOpenActionPerformed

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnSaveActionPerformed
    {//GEN-HEADEREND:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAddActionPerformed
    {//GEN-HEADEREND:event_jBtnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnUndoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnUndoActionPerformed
    {//GEN-HEADEREND:event_jBtnUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnUndoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnOpen;
    private javax.swing.JButton jBtnRemove;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnUndo;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLblFile;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuEditAdd;
    private javax.swing.JMenuItem jMenuEditRemove;
    private javax.swing.JMenuItem jMenuEditUndo;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuFileOpen;
    private javax.swing.JMenuItem jMenuFileSave;
    private javax.swing.JPanel jPanel;
    private javax.swing.JMenuItem jPopupAdd;
    private javax.swing.JPopupMenu jPopupMenuAddressbook;
    private javax.swing.JPopupMenu jPopupMenuOpen;
    private javax.swing.JMenuItem jPopupOnFileOpen;
    private javax.swing.JMenuItem jPopupOpen;
    private javax.swing.JMenuItem jPopupRemove;
    private javax.swing.JMenuItem jPopupSave;
    private javax.swing.JMenuItem jPopupUndo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jFileChooser
     */
    public javax.swing.JFileChooser getjFileChooser()
    {
        return jFileChooser;
    }

}
